### ISSUE TITLE
Cannot import MessageDict

### ISSUE THREAD

**Issue by fcaldas** [cakebread/yolk#37]
Hi

  I am trying to use yolk to list the versions of google-cloud-pubsub but am getting the following errors:

```
fcaldas@lipexingest:~$ yolk -V google-cloud-pubsub                                                                                                                                                                 
Traceback (most recent call last):
  File "/usr/local/bin/yolk", line 7, in <module>
    from yolk.cli import main
  File "/usr/local/lib/python2.7/dist-packages/yolk/cli.py", line 29, in <module>
    import pkg_resources
  File "/home/fcaldas/google_appengine/pkg_resources/__init__.py", line 3038, in <module>
    @_call_aside
  File "/home/fcaldas/google_appengine/pkg_resources/__init__.py", line 3022, in _call_aside
    f(*args, **kwargs)
  File "/home/fcaldas/google_appengine/pkg_resources/__init__.py", line 3066, in _initialize_master_working_set
    for dist in working_set
  File "/home/fcaldas/google_appengine/pkg_resources/__init__.py", line 3066, in <genexpr>
    for dist in working_set
  File "/home/fcaldas/google_appengine/pkg_resources/__init__.py", line 2597, in activate
    declare_namespace(pkg)
  File "/home/fcaldas/google_appengine/pkg_resources/__init__.py", line 2165, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/home/fcaldas/google_appengine/pkg_resources/__init__.py", line 2100, in _handle_ns
    loader.load_module(packageName)
  File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/home/fcaldas/google-cloud-sdk/platform/google_appengine/google/cloud/logging/__init__.py", line 21, in <module>
    from google.cloud.logging.client import Client
  File "/home/fcaldas/google-cloud-sdk/platform/google_appengine/google/cloud/logging/client.py", line 38, in <module>
    from google.cloud.logging.handlers import CloudLoggingHandler
  File "/home/fcaldas/google-cloud-sdk/platform/google_appengine/google/cloud/logging/handlers/__init__.py", line 17, in <module>
    from google.cloud.logging.handlers.app_engine import AppEngineHandler
  File "/home/fcaldas/google-cloud-sdk/platform/google_appengine/google/cloud/logging/handlers/app_engine.py", line 24, in <module>
    from google.cloud.logging.handlers.handlers import CloudLoggingHandler
  File "/home/fcaldas/google-cloud-sdk/platform/google_appengine/google/cloud/logging/handlers/handlers.py", line 20, in <module>
    from google.cloud.logging.logger import _GLOBAL_RESOURCE
  File "/home/fcaldas/google-cloud-sdk/platform/google_appengine/google/cloud/logging/logger.py", line 17, in <module>
    from google.protobuf.json_format import MessageToDict
ImportError: cannot import name MessageToDict

```

Protobuf is currently installed and in version 3.4, any ideas on how to fix this?

**Comment by fcaldas** [comment]
Sorry, this was an error on my environment, reinstalled all packages with pip and it went away.
