### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by itJunky** [cakebread/yolk#38]
How can i fix it?

```
# yolk -V py2deb
Traceback (most recent call last):
  File "/usr/local/bin/yolk", line 7, in <module>
    from yolk.cli import main
  File "/usr/local/lib/python3.4/dist-packages/yolk/cli.py", line 262
    print " %s %s (%s)" % (project_name, dist.version,
                      ^
SyntaxError: invalid syntax
```

yolk-0.4.3 installed by pip3

**Comment by hoefling** [comment]
Install ``yolk3k`` for Python 3.
